{
 "title": "Delfin Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "storageid", "label": "Storage ID" }
  ]
 },
 "panels": [
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Response Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "storage_response_time" }
   ]
  },
  { "title": "Storage Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Storage Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "storage_bandwidth", "legendFormat": "Bandwidth" }
   ]
  },
  {
   "title": "Storage Read Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "storage_read_bandwidth", "legendFormat": "Read BW: {{storage_id}}" }
   ]
  },
  {
   "title": "Storage Write Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storage_write_bandwidth",
     "legendFormat": "Write Bandwidth: {{storage_id}}"
    }
   ]
  },
  { "title": "Storage Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Storage Throughput",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "storage_throughput", "legendFormat": "Throughput" }
   ]
  },
  {
   "title": "Storage Read Throughput",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "storage_read_throughput", "legendFormat": "Read Throughput" }
   ]
  },
  {
   "title": "Storage Write Throughput",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "storage_write_throughput", "legendFormat": "Write Throughput" }
   ]
  }
 ]
}